//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_BOX_H_
#define COMMPERCEPTION_BOX_H_

#include "CommPerception/BoxCore.hh"

namespace CommPerception {
		
class Box : public BoxCore {
	public:
		// default constructors
		Box();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// Box(const CommPerception::CommPoint2d &p1, const CommPerception::CommPoint2d &p2, const CommPerception::CommPoint2d &p3, const CommPerception::CommPoint2d &p4);
		
		Box(const BoxCore &box);
		Box(const DATATYPE &box);
		virtual ~Box();
		
		// use framework specific getter and setter methods from core (base) class
		using BoxCore::get;
		using BoxCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const Box &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommPerception */
#endif /* COMMPERCEPTION_BOX_H_ */
