//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------

#include "CommPerception/Box.hh"

using namespace CommPerception;

Box::Box()
:	BoxCore()
{  }


/**
 * Constructor to set all values.
 * NOTE that you have to keep this constructor consistent with the model!
 * Use  at your own choice.
 *
 * The preferred way to set values for initialization is:
 *      CommRepository::MyCommObject obj;
 *      obj.setX(1).setY(2).setZ(3)...;
Box::Box(const CommPerception::CommPoint2d &p1, const CommPerception::CommPoint2d &p2, const CommPerception::CommPoint2d &p3, const CommPerception::CommPoint2d &p4)
:	BoxCore() // base constructor sets default values as defined in the model
{
	setP1(p1);
	setP2(p2);
	setP3(p3);
	setP4(p4);
}
 */

Box::Box(const BoxCore &box)
:	BoxCore(box)
{  }

Box::Box(const DATATYPE &box)
:	BoxCore(box)
{  }

Box::~Box()
{  }
