//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------

#include "CommPerception/Color.hh"

using namespace CommPerception;

Color::Color()
:	ColorCore()
{  }


/**
 * Constructor to set all values.
 * NOTE that you have to keep this constructor consistent with the model!
 * Use  at your own choice.
 *
 * The preferred way to set values for initialization is:
 *      CommRepository::MyCommObject obj;
 *      obj.setX(1).setY(2).setZ(3)...;
Color::Color(const CommPerception::Colors &name, const CommPerception::HSVSpace &min_range, const CommPerception::HSVSpace &max_range)
:	ColorCore() // base constructor sets default values as defined in the model
{
	setName(name);
	setMin_range(min_range);
	setMax_range(max_range);
}
 */

Color::Color(const ColorCore &color)
:	ColorCore(color)
{  }

Color::Color(const DATATYPE &color)
:	ColorCore(color)
{  }

Color::~Color()
{  }
