//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_COMMPOINT3D_H_
#define COMMPERCEPTION_COMMPOINT3D_H_

#include "CommPerception/CommPoint3dCore.hh"

namespace CommPerception {
		
class CommPoint3d : public CommPoint3dCore {
	public:
		// default constructors
		CommPoint3d();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommPoint3d(const double &x = 0.0, const double &y = 0.0, const double &z = 0.0);
		
		CommPoint3d(const CommPoint3dCore &commPoint3d);
		CommPoint3d(const DATATYPE &commPoint3d);
		virtual ~CommPoint3d();
		
		// use framework specific getter and setter methods from core (base) class
		using CommPoint3dCore::get;
		using CommPoint3dCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommPoint3d &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommPerception */
#endif /* COMMPERCEPTION_COMMPOINT3D_H_ */
