//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_COMMLABEL_H_
#define COMMPERCEPTION_COMMLABEL_H_

#include "CommPerception/CommLabelCore.hh"

namespace CommPerception {
		
class CommLabel : public CommLabelCore {
	public:
		// default constructors
		CommLabel();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommLabel(const std::string &name);
		
		CommLabel(const CommLabelCore &commLabel);
		CommLabel(const DATATYPE &commLabel);
		virtual ~CommLabel();
		
		// use framework specific getter and setter methods from core (base) class
		using CommLabelCore::get;
		using CommLabelCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommLabel &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommPerception */
#endif /* COMMPERCEPTION_COMMLABEL_H_ */
