//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_COMMOBJECTPROPERTIES_H_
#define COMMPERCEPTION_COMMOBJECTPROPERTIES_H_

#include "CommPerception/CommObjectPropertiesCore.hh"

namespace CommPerception {
		
class CommObjectProperties : public CommObjectPropertiesCore {
	public:
		// default constructors
		CommObjectProperties();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommObjectProperties(const unsigned int &object_id, const std::string &object_type, const CommBasicObjects::CommPose3d &pose, const CommBasicObjects::CommPosition3d &dimension, const std::vector<CommObjectRecognitionObjects::CommObjectBelief> &beliefs, const CommObjectRecognitionObjects::CommTriMesh &mesh, const std::vector<CommObjectRecognitionObjects::CommObjectRelation> &relations, const std::vector<CommBasicObjects::CommPose3d> &objectSurfacePoses, const bool &is_valid = false, const double &fill_level = -1.0);
		
		CommObjectProperties(const CommObjectPropertiesCore &commObjectProperties);
		CommObjectProperties(const DATATYPE &commObjectProperties);
		virtual ~CommObjectProperties();
		
		// use framework specific getter and setter methods from core (base) class
		using CommObjectPropertiesCore::get;
		using CommObjectPropertiesCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommObjectProperties &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommPerception */
#endif /* COMMPERCEPTION_COMMOBJECTPROPERTIES_H_ */
