//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_COMMPERSONINF_H_
#define COMMPERCEPTION_COMMPERSONINF_H_

#include "CommPerception/CommPersonInfCore.hh"

namespace CommPerception {
		
class CommPersonInf : public CommPersonInfCore {
	public:
		// default constructors
		CommPersonInf();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommPersonInf(const std::string &name, const CommPerception::ROI &roi, const double &pos = 1.0);
		
		CommPersonInf(const CommPersonInfCore &commPersonInf);
		CommPersonInf(const DATATYPE &commPersonInf);
		virtual ~CommPersonInf();
		
		// use framework specific getter and setter methods from core (base) class
		using CommPersonInfCore::get;
		using CommPersonInfCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommPersonInf &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommPerception */
#endif /* COMMPERCEPTION_COMMPERSONINF_H_ */
