//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_HSVSPACE_H_
#define COMMPERCEPTION_HSVSPACE_H_

#include "CommPerception/HSVSpaceCore.hh"

namespace CommPerception {
		
class HSVSpace : public HSVSpaceCore {
	public:
		// default constructors
		HSVSpace();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// HSVSpace(const double &h = 0.0, const double &s = 0.0, const double &v = 0.0);
		
		HSVSpace(const HSVSpaceCore &hSVSpace);
		HSVSpace(const DATATYPE &hSVSpace);
		virtual ~HSVSpace();
		
		// use framework specific getter and setter methods from core (base) class
		using HSVSpaceCore::get;
		using HSVSpaceCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const HSVSpace &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommPerception */
#endif /* COMMPERCEPTION_HSVSPACE_H_ */
