//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_OBJECTCORE_H_
#define COMMPERCEPTION_OBJECTCORE_H_

#include "CommPerception/ObjectCoreCore.hh"

namespace CommPerception {
		
class ObjectCore : public ObjectCoreCore {
	public:
		// default constructors
		ObjectCore();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// ObjectCore(const bool &is_valid, const unsigned int &object_id, const std::string &object_type, const CommPerception::CommPoint2d &point2d, const CommBasicObjects::CommPose3d &pose, const CommObjectRecognitionObjects::CommObjectRelation &relations, const CommBasicObjects::CommPose3d &surface_poses, const double &fill_level = -1.0);
		
		ObjectCore(const ObjectCoreCore &objectCore);
		ObjectCore(const DATATYPE &objectCore);
		virtual ~ObjectCore();
		
		// use framework specific getter and setter methods from core (base) class
		using ObjectCoreCore::get;
		using ObjectCoreCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const ObjectCore &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommPerception */
#endif /* COMMPERCEPTION_OBJECTCORE_H_ */
