//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommPerception/BoxACE.hh"
#include <ace/SString.h>
#include "CommBasicObjects/CommPosition3dACE.hh"

// serialization operator for element Box
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommPerceptionIDL::Box &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element p1
	good_bit = good_bit && cdr << data.p1;
	// serialize list-element p2
	good_bit = good_bit && cdr << data.p2;
	// serialize list-element p3
	good_bit = good_bit && cdr << data.p3;
	// serialize list-element p4
	good_bit = good_bit && cdr << data.p4;
	
	return good_bit;
}

// de-serialization operator for element Box
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommPerceptionIDL::Box &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize type element p1
	good_bit = good_bit && cdr >> data.p1;
	// deserialize type element p2
	good_bit = good_bit && cdr >> data.p2;
	// deserialize type element p3
	good_bit = good_bit && cdr >> data.p3;
	// deserialize type element p4
	good_bit = good_bit && cdr >> data.p4;
	
	return good_bit;
}

// serialization operator for CommunicationObject Box
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommPerception::Box &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject Box
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommPerception::Box &obj)
{
	return cdr >> obj.set();
}
