//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommPerception/BoxCore.hh"

// serialization/deserialization operators
//#include "CommPerception/BoxACE.hh"

// include the hash.idl containing the hash constant
#include "hash.hh"
#include <assert.h>
#include <cstring>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

#ifdef ENABLE_HASH
	#include <boost/functional/hash.hpp>
#endif

namespace CommPerception 
{
	const char* BoxCore::getCompiledHash()
	{
		return CommPerceptionIDL::REPO_HASH;
	}
	
	void BoxCore::getAllHashValues(std::list<std::string> &hashes)
	{
		// get own hash value
		hashes.push_back(getCompiledHash());
		// get hash value(s) for CommBasicObjects::CommPosition3d(idl_Box.p1)
		CommBasicObjects::CommPosition3d::getAllHashValues(hashes);
		// get hash value(s) for CommBasicObjects::CommPosition3d(idl_Box.p2)
		CommBasicObjects::CommPosition3d::getAllHashValues(hashes);
		// get hash value(s) for CommBasicObjects::CommPosition3d(idl_Box.p3)
		CommBasicObjects::CommPosition3d::getAllHashValues(hashes);
		// get hash value(s) for CommBasicObjects::CommPosition3d(idl_Box.p4)
		CommBasicObjects::CommPosition3d::getAllHashValues(hashes);
	}
	
	void BoxCore::checkAllHashValues(std::list<std::string> &hashes)
	{
		// check own hash value
		if (strcmp(getCompiledHash(), hashes.front().c_str()) != 0)
		{
			std::cerr << "###################################################" << std::endl;
			std::cerr << "WARNING: HASHES OF COMMUNICATION OBJECTS MISSMATCH!" << std::endl;
			std::cerr << "BoxCore hash" << std::endl;
			std::cerr << "Expected: " << getCompiledHash() << std::endl;
			std::cerr << "Received: " << hashes.front() << std::endl;
			std::cerr << "###################################################" << std::endl;
		}
		assert(strcmp(getCompiledHash(), hashes.front().c_str()) == 0);
		hashes.pop_front();
		
		// check hash value(s) for CommBasicObjects::CommPosition3d(idl_Box.p1)
		CommBasicObjects::CommPosition3d::checkAllHashValues(hashes);
		// check hash value(s) for CommBasicObjects::CommPosition3d(idl_Box.p2)
		CommBasicObjects::CommPosition3d::checkAllHashValues(hashes);
		// check hash value(s) for CommBasicObjects::CommPosition3d(idl_Box.p3)
		CommBasicObjects::CommPosition3d::checkAllHashValues(hashes);
		// check hash value(s) for CommBasicObjects::CommPosition3d(idl_Box.p4)
		CommBasicObjects::CommPosition3d::checkAllHashValues(hashes);
	}
	
	#ifdef ENABLE_HASH
	size_t BoxCore::generateDataHash(const DATATYPE &data)
	{
		size_t seed = 0;
		
		seed += CommBasicObjects::CommPosition3d::generateDataHash(data.p1);
		seed += CommBasicObjects::CommPosition3d::generateDataHash(data.p2);
		seed += CommBasicObjects::CommPosition3d::generateDataHash(data.p3);
		seed += CommBasicObjects::CommPosition3d::generateDataHash(data.p4);
		
		return seed;
	}
	#endif
	
	// default constructor
	BoxCore::BoxCore()
	:	idl_Box()
	{  
		setP1(CommBasicObjects::CommPosition3d());
		setP2(CommBasicObjects::CommPosition3d());
		setP3(CommBasicObjects::CommPosition3d());
		setP4(CommBasicObjects::CommPosition3d());
	}
	
	BoxCore::BoxCore(const DATATYPE &data)
	:	idl_Box(data)
	{  }

	BoxCore::~BoxCore()
	{  }
	
	void BoxCore::to_ostream(std::ostream &os) const
	{
	  os << "Box(";
	  getP1().to_ostream(os);
	  getP2().to_ostream(os);
	  getP3().to_ostream(os);
	  getP4().to_ostream(os);
	  os << ") ";
	}
	
	// convert to xml stream
	void BoxCore::to_xml(std::ostream &os, const std::string &indent) const {
		os << indent << "<p1>";
		getP1().to_xml(os, indent);
		os << indent << "</p1>";
		os << indent << "<p2>";
		getP2().to_xml(os, indent);
		os << indent << "</p2>";
		os << indent << "<p3>";
		getP3().to_xml(os, indent);
		os << indent << "</p3>";
		os << indent << "<p4>";
		getP4().to_xml(os, indent);
		os << indent << "</p4>";
	}
	
	// restore from xml stream
	void BoxCore::from_xml(std::istream &is) {
		static const Smart::KnuthMorrisPratt kmp_p1("<p1>");
		static const Smart::KnuthMorrisPratt kmp_p2("<p2>");
		static const Smart::KnuthMorrisPratt kmp_p3("<p3>");
		static const Smart::KnuthMorrisPratt kmp_p4("<p4>");
		
		if(kmp_p1.search(is)) {
			CommBasicObjects::CommPosition3d p1Item;
			p1Item.from_xml(is);
			setP1(p1Item);
		}
		if(kmp_p2.search(is)) {
			CommBasicObjects::CommPosition3d p2Item;
			p2Item.from_xml(is);
			setP2(p2Item);
		}
		if(kmp_p3.search(is)) {
			CommBasicObjects::CommPosition3d p3Item;
			p3Item.from_xml(is);
			setP3(p3Item);
		}
		if(kmp_p4.search(is)) {
			CommBasicObjects::CommPosition3d p4Item;
			p4Item.from_xml(is);
			setP4(p4Item);
		}
	}
	
	/*
	void BoxCore::get(ACE_Message_Block *&msg) const
	{
		// start with a default internal buffer size(will automatically grow if needed)
		ACE_OutputCDR cdr(ACE_DEFAULT_CDR_BUFSIZE);
		
		CommPerceptionIDL::HashList hashes;
		getAllHashValues(hashes);
		cdr << static_cast<ACE_CDR::Long>(hashes.size());
		for(CommPerceptionIDL::HashList::const_iterator it=hashes.begin(); it!=hashes.end(); it++)
		{
			cdr << ACE_CString(it->c_str());
		}
		
		// Here the actual serialization takes place using the OutputCDR serialization operator<<
		// (see BoxACE.hh)
		cdr << idl_Box;
		
	#ifdef ENABLE_HASH
		ACE_CDR::ULong data_hash = generateDataHash(idl_Box);
		cdr << data_hash;
		// std::cout << "BoxCore: current data hash: " << data_hash << std::endl;
	#endif
		
		// return a shallow copy of the serialized message 
		// (no data is actually copied, only the internal reference counter is incremented)
		// in order to prevent memory leaks the caller of this get(msg) method must
		// manually free the memory by calling the release() method of the message block msg
		msg = cdr.begin()->duplicate();
	}
	
	void BoxCore::set(const ACE_Message_Block *msg)
	{
		ACE_InputCDR cdr(msg);
	
		CommPerceptionIDL::HashList hashes;
		ACE_CDR::Long hashes_size;
		cdr >> hashes_size;
		for(int i=0; i<hashes_size; ++i) 
		{
			ACE_CString hash;
			cdr >> hash;
			hashes.push_back(hash.c_str());
		}
		checkAllHashValues(hashes);
		
		// Here the actual de-serialization takes place using the InputCDR serialization operator>>
		// (see BoxACE.hh)
		cdr >> idl_Box;
		
	#ifdef ENABLE_HASH
		ACE_CDR::Long data_hash;
		cdr >> data_hash;
		ACE_CDR::Long own_hash = generateDataHash(idl_Box);
		assert(data_hash == own_hash);
		// std::cout << "BoxCore: own data hash: " << own_hash << "; received data hash: " << data_hash << std::endl;
	#endif
	}
	*/
} /* namespace CommPerception */
