//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_BOX_DATA_H_
#define COMMPERCEPTION_BOX_DATA_H_

#include "CommBasicObjects/CommPosition3dData.hh"


namespace CommPerceptionIDL 
{
	struct Box
	{
		CommBasicObjectsIDL::CommPosition3d p1;
		CommBasicObjectsIDL::CommPosition3d p2;
		CommBasicObjectsIDL::CommPosition3d p3;
		CommBasicObjectsIDL::CommPosition3d p4;
  	};
};

#endif /* COMMPERCEPTION_BOX_DATA_H_ */
