//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_COLOR_DATA_H_
#define COMMPERCEPTION_COLOR_DATA_H_

#include "CommPerception/HSVSpaceData.hh"
#include "CommPerception/enumColorsData.hh"


namespace CommPerceptionIDL 
{
	struct Color
	{
		CommPerceptionIDL::Colors name;
		CommPerceptionIDL::HSVSpace min_range;
		CommPerceptionIDL::HSVSpace max_range;
  	};
};

#endif /* COMMPERCEPTION_COLOR_DATA_H_ */
