//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_COLOR_CORE_H_
#define COMMPERCEPTION_COLOR_CORE_H_

#include "CommPerception/ColorData.hh"
#include "CommPerception/HSVSpace.hh"
#include "CommPerception/enumColors.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommPerception {
	
class ColorCore {
protected:
	// data structure
	CommPerceptionIDL::Color idl_Color;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommPerceptionIDL::Color DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	ColorCore();
	ColorCore(const DATATYPE &data);
	// default destructor
	virtual ~ColorCore();
	
	const DATATYPE& get() const { return idl_Color; }
	operator const DATATYPE&() const { return idl_Color; }
	DATATYPE& set() { return idl_Color; }

	static inline std::string identifier(void) { return "CommPerception::Color"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Name
	inline CommPerception::Colors getName() const { return CommPerception::Colors(idl_Color.name); }
	inline ColorCore& setName(const CommPerception::Colors &name) { idl_Color.name = name; return *this; }
	
	// getter and setter for element Min_range
	inline CommPerception::HSVSpace getMin_range() const { return CommPerception::HSVSpace(idl_Color.min_range); }
	inline ColorCore& setMin_range(const CommPerception::HSVSpace &min_range) { idl_Color.min_range = min_range; return *this; }
	
	// getter and setter for element Max_range
	inline CommPerception::HSVSpace getMax_range() const { return CommPerception::HSVSpace(idl_Color.max_range); }
	inline ColorCore& setMax_range(const CommPerception::HSVSpace &max_range) { idl_Color.max_range = max_range; return *this; }
};

} /* namespace CommPerception */
#endif /* COMMPERCEPTION_COLOR_CORE_H_ */
