//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_COMMINFDETECTION_CORE_H_
#define COMMPERCEPTION_COMMINFDETECTION_CORE_H_

#include "CommPerception/CommInfDetectionData.hh"
#include "CommPerception/Color.hh"
#include "CommPerception/ROI.hh"
#include "CommPerception/Shape.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommPerception {
	
class CommInfDetectionCore {
protected:
	// data structure
	CommPerceptionIDL::CommInfDetection idl_CommInfDetection;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommPerceptionIDL::CommInfDetection DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommInfDetectionCore();
	CommInfDetectionCore(const DATATYPE &data);
	// default destructor
	virtual ~CommInfDetectionCore();
	
	const DATATYPE& get() const { return idl_CommInfDetection; }
	operator const DATATYPE&() const { return idl_CommInfDetection; }
	DATATYPE& set() { return idl_CommInfDetection; }

	static inline std::string identifier(void) { return "CommPerception::CommInfDetection"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Shape
	inline CommPerception::Shape getShape() const { return CommPerception::Shape(idl_CommInfDetection.shape); }
	inline CommInfDetectionCore& setShape(const CommPerception::Shape &shape) { idl_CommInfDetection.shape = shape; return *this; }
	
	// getter and setter for element Color
	inline CommPerception::Color getColor() const { return CommPerception::Color(idl_CommInfDetection.color); }
	inline CommInfDetectionCore& setColor(const CommPerception::Color &color) { idl_CommInfDetection.color = color; return *this; }
	
	// getter and setter for element Roi
	inline CommPerception::ROI getRoi() const { return CommPerception::ROI(idl_CommInfDetection.roi); }
	inline CommInfDetectionCore& setRoi(const CommPerception::ROI &roi) { idl_CommInfDetection.roi = roi; return *this; }
};

} /* namespace CommPerception */
#endif /* COMMPERCEPTION_COMMINFDETECTION_CORE_H_ */
