//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_COMMPERSONINF_CORE_H_
#define COMMPERCEPTION_COMMPERSONINF_CORE_H_

#include "CommPerception/CommPersonInfData.hh"
#include "CommBasicObjects/CommPose3d.hh"
#include "CommPerception/ROI.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommPerception {
	
class CommPersonInfCore {
protected:
	// data structure
	CommPerceptionIDL::CommPersonInf idl_CommPersonInf;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommPerceptionIDL::CommPersonInf DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommPersonInfCore();
	CommPersonInfCore(const DATATYPE &data);
	// default destructor
	virtual ~CommPersonInfCore();
	
	const DATATYPE& get() const { return idl_CommPersonInf; }
	operator const DATATYPE&() const { return idl_CommPersonInf; }
	DATATYPE& set() { return idl_CommPersonInf; }

	static inline std::string identifier(void) { return "CommPerception::CommPersonInf"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Pose
	inline CommBasicObjects::CommPose3d getPose() const { return CommBasicObjects::CommPose3d(idl_CommPersonInf.pose); }
	inline CommPersonInfCore& setPose(const CommBasicObjects::CommPose3d &pose) { idl_CommPersonInf.pose = pose; return *this; }
	
	// getter and setter for element Name
	inline std::string getName() const { return idl_CommPersonInf.name; }
	inline CommPersonInfCore& setName(const std::string &name) { idl_CommPersonInf.name = name; return *this; }
	
	// getter and setter for element Roi
	inline CommPerception::ROI getRoi() const { return CommPerception::ROI(idl_CommPersonInf.roi); }
	inline CommPersonInfCore& setRoi(const CommPerception::ROI &roi) { idl_CommPersonInf.roi = roi; return *this; }
};

} /* namespace CommPerception */
#endif /* COMMPERCEPTION_COMMPERSONINF_CORE_H_ */
