//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_COMMOBJECTPROPERTIES_ACE_H_
#define COMMPERCEPTION_COMMOBJECTPROPERTIES_ACE_H_

#include "CommPerception/CommObjectProperties.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure CommObjectProperties
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommPerceptionIDL::CommObjectProperties &data);

// de-serialization operator for DataStructure CommObjectProperties
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommPerceptionIDL::CommObjectProperties &data);

// serialization operator for CommunicationObject CommObjectProperties
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommPerception::CommObjectProperties &obj);

// de-serialization operator for CommunicationObject CommObjectProperties
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommPerception::CommObjectProperties &obj);

#endif /* COMMPERCEPTION_COMMOBJECTPROPERTIES_ACE_H_ */
