//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommPerception/CommPoint2dACE.hh"
#include <ace/SString.h>

// serialization operator for element CommPoint2d
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommPerceptionIDL::CommPoint2d &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element x
	good_bit = good_bit && cdr.write_double(data.x);
	// serialize list-element y
	good_bit = good_bit && cdr.write_double(data.y);
	
	return good_bit;
}

// de-serialization operator for element CommPoint2d
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommPerceptionIDL::CommPoint2d &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize type element x
	good_bit = good_bit && cdr.read_double(data.x);
	// deserialize type element y
	good_bit = good_bit && cdr.read_double(data.y);
	
	return good_bit;
}

// serialization operator for CommunicationObject CommPoint2d
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommPerception::CommPoint2d &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject CommPoint2d
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommPerception::CommPoint2d &obj)
{
	return cdr >> obj.set();
}
