//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_COMMPERSONINF_DATA_H_
#define COMMPERCEPTION_COMMPERSONINF_DATA_H_

#include "CommPerception/ROIData.hh"
#include "CommBasicObjects/CommPose3dData.hh"

#include <string>

namespace CommPerceptionIDL 
{
	struct CommPersonInf
	{
		CommBasicObjectsIDL::CommPose3d pose;
		std::string name;
		CommPerceptionIDL::ROI roi;
  	};
};

#endif /* COMMPERCEPTION_COMMPERSONINF_DATA_H_ */
