//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_COMMOBJECTPROPERTIES_DATA_H_
#define COMMPERCEPTION_COMMOBJECTPROPERTIES_DATA_H_

#include "CommObjectRecognitionObjects/CommObjectRelationData.hh"
#include "CommBasicObjects/CommPose3dData.hh"

#include <vector>
#include <string>

namespace CommPerceptionIDL 
{
	typedef std::vector<CommObjectRecognitionObjectsIDL::CommObjectRelation> CommObjectProperties_relations_type;
	typedef std::vector<CommBasicObjectsIDL::CommPose3d> CommObjectProperties_surface_poses_type;
	struct CommObjectProperties
	{
		bool is_valid;
		unsigned int object_id;
		std::string object_type;
		CommBasicObjectsIDL::CommPose3d pose;
		CommObjectProperties_relations_type relations;
		double fill_level;
		CommObjectProperties_surface_poses_type surface_poses;
  	};
};

#endif /* COMMPERCEPTION_COMMOBJECTPROPERTIES_DATA_H_ */
