//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommPerception/CommPersonDetectionACE.hh"
#include <ace/SString.h>
#include "CommPerception/CommPersonInfACE.hh"

// serialization operator for element CommPersonDetection
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommPerceptionIDL::CommPersonDetection &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element persons
	good_bit = good_bit && cdr << ACE_Utils::truncate_cast<ACE_CDR::ULong>(data.persons.size());
	std::vector<CommPerceptionIDL::CommPersonInf>::const_iterator data_personsIt;
	for(data_personsIt=data.persons.begin(); data_personsIt!=data.persons.end(); data_personsIt++) {
		good_bit = good_bit && cdr << *data_personsIt;
	}
	
	return good_bit;
}

// de-serialization operator for element CommPersonDetection
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommPerceptionIDL::CommPersonDetection &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize list-type element persons
	ACE_CDR::ULong data_personsNbr;
	good_bit = good_bit && cdr >> data_personsNbr;
	data.persons.clear();
	CommPerceptionIDL::CommPersonInf data_personsItem;
	for(ACE_CDR::ULong i=0; i<data_personsNbr; ++i) {
		good_bit = good_bit && cdr >> data_personsItem;
		data.persons.push_back(data_personsItem);
	}
	
	return good_bit;
}

// serialization operator for CommunicationObject CommPersonDetection
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommPerception::CommPersonDetection &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject CommPersonDetection
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommPerception::CommPersonDetection &obj)
{
	return cdr >> obj.set();
}
