//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommPerception/CommPersonDetectionCore.hh"

// serialization/deserialization operators
//#include "CommPerception/CommPersonDetectionACE.hh"

// include the hash.idl containing the hash constant
#include "hash.hh"
#include <assert.h>
#include <cstring>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

#ifdef ENABLE_HASH
	#include <boost/functional/hash.hpp>
#endif

namespace CommPerception 
{
	const char* CommPersonDetectionCore::getCompiledHash()
	{
		return CommPerceptionIDL::REPO_HASH;
	}
	
	void CommPersonDetectionCore::getAllHashValues(std::list<std::string> &hashes)
	{
		// get own hash value
		hashes.push_back(getCompiledHash());
		// get hash value(s) for CommPerception::CommPersonInf(idl_CommPersonDetection.persons)
		CommPerception::CommPersonInf::getAllHashValues(hashes);
	}
	
	void CommPersonDetectionCore::checkAllHashValues(std::list<std::string> &hashes)
	{
		// check own hash value
		if (strcmp(getCompiledHash(), hashes.front().c_str()) != 0)
		{
			std::cerr << "###################################################" << std::endl;
			std::cerr << "WARNING: HASHES OF COMMUNICATION OBJECTS MISSMATCH!" << std::endl;
			std::cerr << "CommPersonDetectionCore hash" << std::endl;
			std::cerr << "Expected: " << getCompiledHash() << std::endl;
			std::cerr << "Received: " << hashes.front() << std::endl;
			std::cerr << "###################################################" << std::endl;
		}
		assert(strcmp(getCompiledHash(), hashes.front().c_str()) == 0);
		hashes.pop_front();
		
		// check hash value(s) for CommPerception::CommPersonInf(idl_CommPersonDetection.persons)
		CommPerception::CommPersonInf::checkAllHashValues(hashes);
	}
	
	#ifdef ENABLE_HASH
	size_t CommPersonDetectionCore::generateDataHash(const DATATYPE &data)
	{
		size_t seed = 0;
		
		std::vector<CommPerceptionIDL::CommPersonInf>::const_iterator data_personsIt;
		for(data_personsIt=data.persons.begin(); data_personsIt!=data.persons.end(); data_personsIt++) {
			seed += CommPerception::CommPersonInf::generateDataHash(*data_personsIt);
		}
		
		return seed;
	}
	#endif
	
	// default constructor
	CommPersonDetectionCore::CommPersonDetectionCore()
	:	idl_CommPersonDetection()
	{  
		setPersons(std::vector<CommPerception::CommPersonInf>());
	}
	
	CommPersonDetectionCore::CommPersonDetectionCore(const DATATYPE &data)
	:	idl_CommPersonDetection(data)
	{  }

	CommPersonDetectionCore::~CommPersonDetectionCore()
	{  }
	
	void CommPersonDetectionCore::to_ostream(std::ostream &os) const
	{
	  os << "CommPersonDetection(";
	  std::vector<CommPerception::CommPersonInf>::const_iterator personsIt;
	  std::vector<CommPerception::CommPersonInf> personsList = getPersonsCopy();
	  for(personsIt=personsList.begin(); personsIt!=personsList.end(); personsIt++) {
	  	personsIt->to_ostream(os);
	  }
	  os << ") ";
	}
	
	// convert to xml stream
	void CommPersonDetectionCore::to_xml(std::ostream &os, const std::string &indent) const {
		size_t counter = 0;
		
		std::vector<CommPerception::CommPersonInf>::const_iterator personsIt;
		std::vector<CommPerception::CommPersonInf> personsList = getPersonsCopy();
		counter = 0;
		os << indent << "<personsList n=\"" << personsList.size() << "\">";
		for(personsIt=personsList.begin(); personsIt!=personsList.end(); personsIt++) {
			os << indent << "<persons i=\"" << counter++ << "\">";
			personsIt->to_xml(os, indent);
			os << indent << "</persons>";
		}
		os << indent << "</personsList>";
	}
	
	// restore from xml stream
	void CommPersonDetectionCore::from_xml(std::istream &is) {
		size_t counter = 0;
		
		static const Smart::KnuthMorrisPratt kmp_personsList("<personsList n=\"");
		static const Smart::KnuthMorrisPratt kmp_persons("\">");
		
		if(kmp_personsList.search(is)) {
			size_t numberElements;
			is >> numberElements;
			CommPerception::CommPersonInf personsItem;
			std::vector<CommPerception::CommPersonInf> personsList;
			kmp_persons.search(is);
			for(counter=0; counter<numberElements; counter++) {
				if(kmp_persons.search(is)) {
					personsItem.from_xml(is);
					personsList.push_back(personsItem);
				}
			}
			setPersons(personsList);
		}
	}
	
	/*
	void CommPersonDetectionCore::get(ACE_Message_Block *&msg) const
	{
		// start with a default internal buffer size(will automatically grow if needed)
		ACE_OutputCDR cdr(ACE_DEFAULT_CDR_BUFSIZE);
		
		CommPerceptionIDL::HashList hashes;
		getAllHashValues(hashes);
		cdr << static_cast<ACE_CDR::Long>(hashes.size());
		for(CommPerceptionIDL::HashList::const_iterator it=hashes.begin(); it!=hashes.end(); it++)
		{
			cdr << ACE_CString(it->c_str());
		}
		
		// Here the actual serialization takes place using the OutputCDR serialization operator<<
		// (see CommPersonDetectionACE.hh)
		cdr << idl_CommPersonDetection;
		
	#ifdef ENABLE_HASH
		ACE_CDR::ULong data_hash = generateDataHash(idl_CommPersonDetection);
		cdr << data_hash;
		// std::cout << "CommPersonDetectionCore: current data hash: " << data_hash << std::endl;
	#endif
		
		// return a shallow copy of the serialized message 
		// (no data is actually copied, only the internal reference counter is incremented)
		// in order to prevent memory leaks the caller of this get(msg) method must
		// manually free the memory by calling the release() method of the message block msg
		msg = cdr.begin()->duplicate();
	}
	
	void CommPersonDetectionCore::set(const ACE_Message_Block *msg)
	{
		ACE_InputCDR cdr(msg);
	
		CommPerceptionIDL::HashList hashes;
		ACE_CDR::Long hashes_size;
		cdr >> hashes_size;
		for(int i=0; i<hashes_size; ++i) 
		{
			ACE_CString hash;
			cdr >> hash;
			hashes.push_back(hash.c_str());
		}
		checkAllHashValues(hashes);
		
		// Here the actual de-serialization takes place using the InputCDR serialization operator>>
		// (see CommPersonDetectionACE.hh)
		cdr >> idl_CommPersonDetection;
		
	#ifdef ENABLE_HASH
		ACE_CDR::Long data_hash;
		cdr >> data_hash;
		ACE_CDR::Long own_hash = generateDataHash(idl_CommPersonDetection);
		assert(data_hash == own_hash);
		// std::cout << "CommPersonDetectionCore: own data hash: " << own_hash << "; received data hash: " << data_hash << std::endl;
	#endif
	}
	*/
} /* namespace CommPerception */
