//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommPerception/CommPersonInfACE.hh"
#include <ace/SString.h>
#include "CommPerception/ROIACE.hh"
#include "CommBasicObjects/CommPose3dACE.hh"

// serialization operator for element CommPersonInf
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommPerceptionIDL::CommPersonInf &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element pose
	good_bit = good_bit && cdr << data.pose;
	// serialize list-element name
	good_bit = good_bit && cdr << ACE_CString(data.name.c_str());
	// serialize list-element roi
	good_bit = good_bit && cdr << data.roi;
	
	return good_bit;
}

// de-serialization operator for element CommPersonInf
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommPerceptionIDL::CommPersonInf &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize type element pose
	good_bit = good_bit && cdr >> data.pose;
	// deserialize string-type element name
	ACE_CString data_name_str;
	good_bit = good_bit && cdr >> data_name_str;
	data.name = data_name_str.c_str();
	// deserialize type element roi
	good_bit = good_bit && cdr >> data.roi;
	
	return good_bit;
}

// serialization operator for CommunicationObject CommPersonInf
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommPerception::CommPersonInf &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject CommPersonInf
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommPerception::CommPersonInf &obj)
{
	return cdr >> obj.set();
}
