//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_COMMPERSONDETECTION_CORE_H_
#define COMMPERCEPTION_COMMPERSONDETECTION_CORE_H_

#include "CommPerception/CommPersonDetectionData.hh"
#include "CommPerception/CommPersonInf.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommPerception {
	
class CommPersonDetectionCore {
protected:
	// data structure
	CommPerceptionIDL::CommPersonDetection idl_CommPersonDetection;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommPerceptionIDL::CommPersonDetection DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommPersonDetectionCore();
	CommPersonDetectionCore(const DATATYPE &data);
	// default destructor
	virtual ~CommPersonDetectionCore();
	
	const DATATYPE& get() const { return idl_CommPersonDetection; }
	operator const DATATYPE&() const { return idl_CommPersonDetection; }
	DATATYPE& set() { return idl_CommPersonDetection; }

	static inline std::string identifier(void) { return "CommPerception::CommPersonDetection"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Persons
	/**
	 * Getter methods for element idl_CommPersonDetection.persons of type vector<CommPerception::CommPersonInf>
	 */
	inline std::vector<CommPerception::CommPersonInf> getPersonsCopy() const { 
		return std::vector<CommPerception::CommPersonInf>(idl_CommPersonDetection.persons.begin(), idl_CommPersonDetection.persons.end());
	}
	inline CommPerception::CommPersonInf getPersonsElemAtPos(const size_t &pos) const {
		return CommPerception::CommPersonInf(idl_CommPersonDetection.persons[pos]);
	}
	inline size_t getPersonsSize() const { return idl_CommPersonDetection.persons.size(); }
	inline bool isPersonsEmpty() const { return idl_CommPersonDetection.persons.empty(); }
	/**
	 * Setter methods for idl_CommPersonDetection.persons of type vector<CommPerception::CommPersonInf>
	 */
	inline CommPersonDetectionCore& setPersons(const std::vector<CommPerception::CommPersonInf> &persons) { 
		idl_CommPersonDetection.persons.assign(persons.begin(), persons.end());
		return *this;
	}
	inline bool setPersonsElemAtPos(const size_t &pos, const CommPerception::CommPersonInf &elem) {
		if(pos < idl_CommPersonDetection.persons.size()) {
			idl_CommPersonDetection.persons[pos] = elem;
			return true;
		}
		return false;
	}
	inline bool insertPersonsVectorAtPos(const size_t &pos, const std::vector<CommPerception::CommPersonInf> &data) {
		if(pos < idl_CommPersonDetection.persons.size()) {
			idl_CommPersonDetection.persons.insert(idl_CommPersonDetection.persons.begin()+pos, data.begin(), data.end());
			return true;
		}
		return false;
	}
	inline void resizePersons(const size_t &size) { idl_CommPersonDetection.persons.resize(size); }
	inline bool erasePersonsElemsAtPos(const size_t &pos, const size_t &nbr_elems) {
		if( (pos+nbr_elems) <= idl_CommPersonDetection.persons.size() ) {
			idl_CommPersonDetection.persons.erase(idl_CommPersonDetection.persons.begin()+pos, idl_CommPersonDetection.persons.begin()+pos+nbr_elems);
			return true;
		}
		return false;
	}
	inline void clearPersons() { idl_CommPersonDetection.persons.clear(); }
};

} /* namespace CommPerception */
#endif /* COMMPERCEPTION_COMMPERSONDETECTION_CORE_H_ */
