//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_HSVSPACE_ACE_H_
#define COMMPERCEPTION_HSVSPACE_ACE_H_

#include "CommPerception/HSVSpace.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure HSVSpace
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommPerceptionIDL::HSVSpace &data);

// de-serialization operator for DataStructure HSVSpace
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommPerceptionIDL::HSVSpace &data);

// serialization operator for CommunicationObject HSVSpace
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommPerception::HSVSpace &obj);

// de-serialization operator for CommunicationObject HSVSpace
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommPerception::HSVSpace &obj);

#endif /* COMMPERCEPTION_HSVSPACE_ACE_H_ */
