//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_OBJECTCORE_ACE_H_
#define COMMPERCEPTION_OBJECTCORE_ACE_H_

#include "CommPerception/ObjectCore.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure ObjectCore
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommPerceptionIDL::ObjectCore &data);

// de-serialization operator for DataStructure ObjectCore
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommPerceptionIDL::ObjectCore &data);

// serialization operator for CommunicationObject ObjectCore
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommPerception::ObjectCore &obj);

// de-serialization operator for CommunicationObject ObjectCore
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommPerception::ObjectCore &obj);

#endif /* COMMPERCEPTION_OBJECTCORE_ACE_H_ */
