//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_OBJECTCORE_DATA_H_
#define COMMPERCEPTION_OBJECTCORE_DATA_H_

#include "CommObjectRecognitionObjects/CommObjectRelationData.hh"
#include "CommPerception/CommPoint2dData.hh"
#include "CommBasicObjects/CommPose3dData.hh"

#include <string>

namespace CommPerceptionIDL 
{
	struct ObjectCore
	{
		bool is_valid;
		unsigned int object_id;
		std::string object_type;
		CommPerceptionIDL::CommPoint2d point2d;
		CommBasicObjectsIDL::CommPose3d pose;
		CommObjectRecognitionObjectsIDL::CommObjectRelation relations;
		double fill_level;
		CommBasicObjectsIDL::CommPose3d surface_poses;
  	};
};

#endif /* COMMPERCEPTION_OBJECTCORE_DATA_H_ */
