//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommPerception/ROIACE.hh"
#include <ace/SString.h>
#include "CommPerception/CommPoint2dACE.hh"

// serialization operator for element ROI
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommPerceptionIDL::ROI &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element point
	good_bit = good_bit && cdr << data.point;
	// serialize list-element width
	good_bit = good_bit && cdr.write_double(data.width);
	// serialize list-element height
	good_bit = good_bit && cdr.write_double(data.height);
	
	return good_bit;
}

// de-serialization operator for element ROI
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommPerceptionIDL::ROI &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize type element point
	good_bit = good_bit && cdr >> data.point;
	// deserialize type element width
	good_bit = good_bit && cdr.read_double(data.width);
	// deserialize type element height
	good_bit = good_bit && cdr.read_double(data.height);
	
	return good_bit;
}

// serialization operator for CommunicationObject ROI
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommPerception::ROI &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject ROI
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommPerception::ROI &obj)
{
	return cdr >> obj.set();
}
