//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_ROI_CORE_H_
#define COMMPERCEPTION_ROI_CORE_H_

#include "CommPerception/ROIData.hh"
#include "CommPerception/CommPoint2d.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommPerception {
	
class ROICore {
protected:
	// data structure
	CommPerceptionIDL::ROI idl_ROI;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommPerceptionIDL::ROI DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	ROICore();
	ROICore(const DATATYPE &data);
	// default destructor
	virtual ~ROICore();
	
	const DATATYPE& get() const { return idl_ROI; }
	operator const DATATYPE&() const { return idl_ROI; }
	DATATYPE& set() { return idl_ROI; }

	static inline std::string identifier(void) { return "CommPerception::ROI"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Point
	inline CommPerception::CommPoint2d getPoint() const { return CommPerception::CommPoint2d(idl_ROI.point); }
	inline ROICore& setPoint(const CommPerception::CommPoint2d &point) { idl_ROI.point = point; return *this; }
	
	// getter and setter for element Width
	inline double getWidth() const { return idl_ROI.width; }
	inline ROICore& setWidth(const double &width) { idl_ROI.width = width; return *this; }
	
	// getter and setter for element Height
	inline double getHeight() const { return idl_ROI.height; }
	inline ROICore& setHeight(const double &height) { idl_ROI.height = height; return *this; }
};

} /* namespace CommPerception */
#endif /* COMMPERCEPTION_ROI_CORE_H_ */
