//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_ROI_DATA_H_
#define COMMPERCEPTION_ROI_DATA_H_

#include "CommPerception/CommPoint2dData.hh"


namespace CommPerceptionIDL 
{
	struct ROI
	{
		CommPerceptionIDL::CommPoint2d point;
		double width;
		double height;
  	};
};

#endif /* COMMPERCEPTION_ROI_DATA_H_ */
