//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPERCEPTION_SHAPE_DATA_H_
#define COMMPERCEPTION_SHAPE_DATA_H_

#include "CommPerception/enumShapesData.hh"


namespace CommPerceptionIDL 
{
	struct Shape
	{
		CommPerceptionIDL::Shapes name;
  	};
};

#endif /* COMMPERCEPTION_SHAPE_DATA_H_ */
