//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMOBJECTRECOGNITIONOBJECTS_COMMOBJECTRECOGNITIONINFORMATION_H_
#define COMMOBJECTRECOGNITIONOBJECTS_COMMOBJECTRECOGNITIONINFORMATION_H_

#include "CommObjectRecognitionObjects/CommObjectRecognitionInformationCore.hh"

namespace CommObjectRecognitionObjects {
		
class CommObjectRecognitionInformation : public CommObjectRecognitionInformationCore {
	public:
		// default constructors
		CommObjectRecognitionInformation();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommObjectRecognitionInformation(const unsigned int &id, const CommObjectRecognitionObjects::ROI &roi);
		
		CommObjectRecognitionInformation(const CommObjectRecognitionInformationCore &commObjectRecognitionInformation);
		CommObjectRecognitionInformation(const DATATYPE &commObjectRecognitionInformation);
		virtual ~CommObjectRecognitionInformation();
		
		// use framework specific getter and setter methods from core (base) class
		using CommObjectRecognitionInformationCore::get;
		using CommObjectRecognitionInformationCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommObjectRecognitionInformation &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommObjectRecognitionObjects */
#endif /* COMMOBJECTRECOGNITIONOBJECTS_COMMOBJECTRECOGNITIONINFORMATION_H_ */
