//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommObjectRecognitionObjects/BGRSpaceACE.hh"
#include <ace/SString.h>

// serialization operator for element BGRSpace
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommObjectRecognitionObjectsIDL::BGRSpace &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element b
	good_bit = good_bit && cdr.write_double(data.b);
	// serialize list-element g
	good_bit = good_bit && cdr.write_double(data.g);
	// serialize list-element r
	good_bit = good_bit && cdr.write_double(data.r);
	
	return good_bit;
}

// de-serialization operator for element BGRSpace
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommObjectRecognitionObjectsIDL::BGRSpace &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize type element b
	good_bit = good_bit && cdr.read_double(data.b);
	// deserialize type element g
	good_bit = good_bit && cdr.read_double(data.g);
	// deserialize type element r
	good_bit = good_bit && cdr.read_double(data.r);
	
	return good_bit;
}

// serialization operator for CommunicationObject BGRSpace
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommObjectRecognitionObjects::BGRSpace &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject BGRSpace
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommObjectRecognitionObjects::BGRSpace &obj)
{
	return cdr >> obj.set();
}
