//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMOBJECTRECOGNITIONOBJECTS_COLOR_DATA_H_
#define COMMOBJECTRECOGNITIONOBJECTS_COLOR_DATA_H_

#include "CommObjectRecognitionObjects/HSVSpaceData.hh"
#include "CommObjectRecognitionObjects/enumColorsData.hh"


namespace CommObjectRecognitionObjectsIDL 
{
	struct Color
	{
		CommObjectRecognitionObjectsIDL::Colors name;
		CommObjectRecognitionObjectsIDL::HSVSpace min_range;
		CommObjectRecognitionObjectsIDL::HSVSpace max_range;
  	};
};

#endif /* COMMOBJECTRECOGNITIONOBJECTS_COLOR_DATA_H_ */
