//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommObjectRecognitionObjects/CommColorDetectionACE.hh"
#include <ace/SString.h>
#include "CommObjectRecognitionObjects/ColorACE.hh"
#include "CommObjectRecognitionObjects/ROIACE.hh"

// serialization operator for element CommColorDetection
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommObjectRecognitionObjectsIDL::CommColorDetection &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element color
	good_bit = good_bit && cdr << data.color;
	// serialize list-element roi
	good_bit = good_bit && cdr << data.roi;
	
	return good_bit;
}

// de-serialization operator for element CommColorDetection
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommObjectRecognitionObjectsIDL::CommColorDetection &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize type element color
	good_bit = good_bit && cdr >> data.color;
	// deserialize type element roi
	good_bit = good_bit && cdr >> data.roi;
	
	return good_bit;
}

// serialization operator for CommunicationObject CommColorDetection
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommObjectRecognitionObjects::CommColorDetection &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject CommColorDetection
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommObjectRecognitionObjects::CommColorDetection &obj)
{
	return cdr >> obj.set();
}
