//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommObjectRecognitionObjects/CommObjectRecognitionInformationCore.hh"

// serialization/deserialization operators
//#include "CommObjectRecognitionObjects/CommObjectRecognitionInformationACE.hh"

// include the hash.idl containing the hash constant
#include "hash.hh"
#include <assert.h>
#include <cstring>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

#ifdef ENABLE_HASH
	#include <boost/functional/hash.hpp>
#endif

namespace CommObjectRecognitionObjects 
{
	const char* CommObjectRecognitionInformationCore::getCompiledHash()
	{
		return CommObjectRecognitionObjectsIDL::REPO_HASH;
	}
	
	void CommObjectRecognitionInformationCore::getAllHashValues(std::list<std::string> &hashes)
	{
		// get own hash value
		hashes.push_back(getCompiledHash());
		// get hash value(s) for CommObjectRecognitionObjects::ROI(idl_CommObjectRecognitionInformation.roi)
		CommObjectRecognitionObjects::ROI::getAllHashValues(hashes);
		// get hash value(s) for CommObjectRecognitionObjects::Color(idl_CommObjectRecognitionInformation.color)
		CommObjectRecognitionObjects::Color::getAllHashValues(hashes);
	}
	
	void CommObjectRecognitionInformationCore::checkAllHashValues(std::list<std::string> &hashes)
	{
		// check own hash value
		if (strcmp(getCompiledHash(), hashes.front().c_str()) != 0)
		{
			std::cerr << "###################################################" << std::endl;
			std::cerr << "WARNING: HASHES OF COMMUNICATION OBJECTS MISSMATCH!" << std::endl;
			std::cerr << "CommObjectRecognitionInformationCore hash" << std::endl;
			std::cerr << "Expected: " << getCompiledHash() << std::endl;
			std::cerr << "Received: " << hashes.front() << std::endl;
			std::cerr << "###################################################" << std::endl;
		}
		assert(strcmp(getCompiledHash(), hashes.front().c_str()) == 0);
		hashes.pop_front();
		
		// check hash value(s) for CommObjectRecognitionObjects::ROI(idl_CommObjectRecognitionInformation.roi)
		CommObjectRecognitionObjects::ROI::checkAllHashValues(hashes);
		// check hash value(s) for CommObjectRecognitionObjects::Color(idl_CommObjectRecognitionInformation.color)
		CommObjectRecognitionObjects::Color::checkAllHashValues(hashes);
	}
	
	#ifdef ENABLE_HASH
	size_t CommObjectRecognitionInformationCore::generateDataHash(const DATATYPE &data)
	{
		size_t seed = 0;
		
		boost::hash_combine(seed, data.id);
		seed += CommObjectRecognitionObjects::ROI::generateDataHash(data.roi);
		seed += CommObjectRecognitionObjects::Color::generateDataHash(data.color);
		
		return seed;
	}
	#endif
	
	// default constructor
	CommObjectRecognitionInformationCore::CommObjectRecognitionInformationCore()
	:	idl_CommObjectRecognitionInformation()
	{  
		setId(0);
		setRoi(CommObjectRecognitionObjects::ROI());
		setColor(CommObjectRecognitionObjects::Color());
	}
	
	CommObjectRecognitionInformationCore::CommObjectRecognitionInformationCore(const DATATYPE &data)
	:	idl_CommObjectRecognitionInformation(data)
	{  }

	CommObjectRecognitionInformationCore::~CommObjectRecognitionInformationCore()
	{  }
	
	void CommObjectRecognitionInformationCore::to_ostream(std::ostream &os) const
	{
	  os << "CommObjectRecognitionInformation(";
	  os << getId() << " ";
	  getRoi().to_ostream(os);
	  getColor().to_ostream(os);
	  os << ") ";
	}
	
	// convert to xml stream
	void CommObjectRecognitionInformationCore::to_xml(std::ostream &os, const std::string &indent) const {
		os << indent << "<id>" << getId() << "</id>";
		os << indent << "<roi>";
		getRoi().to_xml(os, indent);
		os << indent << "</roi>";
		os << indent << "<color>";
		getColor().to_xml(os, indent);
		os << indent << "</color>";
	}
	
	// restore from xml stream
	void CommObjectRecognitionInformationCore::from_xml(std::istream &is) {
		static const Smart::KnuthMorrisPratt kmp_id("<id>");
		static const Smart::KnuthMorrisPratt kmp_roi("<roi>");
		static const Smart::KnuthMorrisPratt kmp_color("<color>");
		
		if(kmp_id.search(is)) {
			unsigned int idItem;
			is >> idItem;
			setId(idItem);
		}
		if(kmp_roi.search(is)) {
			CommObjectRecognitionObjects::ROI roiItem;
			roiItem.from_xml(is);
			setRoi(roiItem);
		}
		if(kmp_color.search(is)) {
			CommObjectRecognitionObjects::Color colorItem;
			colorItem.from_xml(is);
			setColor(colorItem);
		}
	}
	
	/*
	void CommObjectRecognitionInformationCore::get(ACE_Message_Block *&msg) const
	{
		// start with a default internal buffer size(will automatically grow if needed)
		ACE_OutputCDR cdr(ACE_DEFAULT_CDR_BUFSIZE);
		
		CommObjectRecognitionObjectsIDL::HashList hashes;
		getAllHashValues(hashes);
		cdr << static_cast<ACE_CDR::Long>(hashes.size());
		for(CommObjectRecognitionObjectsIDL::HashList::const_iterator it=hashes.begin(); it!=hashes.end(); it++)
		{
			cdr << ACE_CString(it->c_str());
		}
		
		// Here the actual serialization takes place using the OutputCDR serialization operator<<
		// (see CommObjectRecognitionInformationACE.hh)
		cdr << idl_CommObjectRecognitionInformation;
		
	#ifdef ENABLE_HASH
		ACE_CDR::ULong data_hash = generateDataHash(idl_CommObjectRecognitionInformation);
		cdr << data_hash;
		// std::cout << "CommObjectRecognitionInformationCore: current data hash: " << data_hash << std::endl;
	#endif
		
		// return a shallow copy of the serialized message 
		// (no data is actually copied, only the internal reference counter is incremented)
		// in order to prevent memory leaks the caller of this get(msg) method must
		// manually free the memory by calling the release() method of the message block msg
		msg = cdr.begin()->duplicate();
	}
	
	void CommObjectRecognitionInformationCore::set(const ACE_Message_Block *msg)
	{
		ACE_InputCDR cdr(msg);
	
		CommObjectRecognitionObjectsIDL::HashList hashes;
		ACE_CDR::Long hashes_size;
		cdr >> hashes_size;
		for(int i=0; i<hashes_size; ++i) 
		{
			ACE_CString hash;
			cdr >> hash;
			hashes.push_back(hash.c_str());
		}
		checkAllHashValues(hashes);
		
		// Here the actual de-serialization takes place using the InputCDR serialization operator>>
		// (see CommObjectRecognitionInformationACE.hh)
		cdr >> idl_CommObjectRecognitionInformation;
		
	#ifdef ENABLE_HASH
		ACE_CDR::Long data_hash;
		cdr >> data_hash;
		ACE_CDR::Long own_hash = generateDataHash(idl_CommObjectRecognitionInformation);
		assert(data_hash == own_hash);
		// std::cout << "CommObjectRecognitionInformationCore: own data hash: " << own_hash << "; received data hash: " << data_hash << std::endl;
	#endif
	}
	*/
} /* namespace CommObjectRecognitionObjects */
