//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMOBJECTRECOGNITIONOBJECTS_SHAPES_ENUM_H_
#define COMMOBJECTRECOGNITIONOBJECTS_SHAPES_ENUM_H_

#include <CommObjectRecognitionObjects/enumShapesData.hh>

#include <string>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace CommObjectRecognitionObjects {
	
	class Shapes {
	private:
		CommObjectRecognitionObjectsIDL::Shapes value;
		
	public:
		enum ENUM_Shapes {
			ENUM_VALUE_UNDEFINED = 0,
			UNDEFINED = 1,
			SPHERE = 2,
			CUBE = 3,
			CYLINDER = 4
		};
		
		// default constructor
		Shapes() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		Shapes(ENUM_Shapes e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type
		Shapes(CommObjectRecognitionObjectsIDL::Shapes e) {
			value = e;
		}
		
		//const CommObjectRecognitionObjectsIDL::Shapes& get() const { return value; }
		
		// ENUM operator
		operator ENUM_Shapes() const {
			return static_cast<ENUM_Shapes>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_Shapes t) const {
			return this->value == t;
		}
		
		std::string to_string() const {
			std::string result = "";
			switch (value) {
				case UNDEFINED:
					result = "Shapes::UNDEFINED";
					break;
				case SPHERE:
					result = "Shapes::SPHERE";
					break;
				case CUBE:
					result = "Shapes::CUBE";
					break;
				case CYLINDER:
					result = "Shapes::CYLINDER";
					break;
				default:
					result = "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const Shapes &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
