//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommObjectRecognitionObjects/HSVSpaceACE.hh"
#include <ace/SString.h>

// serialization operator for element HSVSpace
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommObjectRecognitionObjectsIDL::HSVSpace &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element h
	good_bit = good_bit && cdr.write_double(data.h);
	// serialize list-element s
	good_bit = good_bit && cdr.write_double(data.s);
	// serialize list-element v
	good_bit = good_bit && cdr.write_double(data.v);
	
	return good_bit;
}

// de-serialization operator for element HSVSpace
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommObjectRecognitionObjectsIDL::HSVSpace &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize type element h
	good_bit = good_bit && cdr.read_double(data.h);
	// deserialize type element s
	good_bit = good_bit && cdr.read_double(data.s);
	// deserialize type element v
	good_bit = good_bit && cdr.read_double(data.v);
	
	return good_bit;
}

// serialization operator for CommunicationObject HSVSpace
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommObjectRecognitionObjects::HSVSpace &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject HSVSpace
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommObjectRecognitionObjects::HSVSpace &obj)
{
	return cdr >> obj.set();
}
