//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommObjectRecognitionObjects/ROICore.hh"

// serialization/deserialization operators
//#include "CommObjectRecognitionObjects/ROIACE.hh"

// include the hash.idl containing the hash constant
#include "hash.hh"
#include <assert.h>
#include <cstring>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

#ifdef ENABLE_HASH
	#include <boost/functional/hash.hpp>
#endif

namespace CommObjectRecognitionObjects 
{
	const char* ROICore::getCompiledHash()
	{
		return CommObjectRecognitionObjectsIDL::REPO_HASH;
	}
	
	void ROICore::getAllHashValues(std::list<std::string> &hashes)
	{
		// get own hash value
		hashes.push_back(getCompiledHash());
		// get hash value(s) for CommObjectRecognitionObjects::CommPoint2d(idl_ROI.point)
		CommObjectRecognitionObjects::CommPoint2d::getAllHashValues(hashes);
	}
	
	void ROICore::checkAllHashValues(std::list<std::string> &hashes)
	{
		// check own hash value
		if (strcmp(getCompiledHash(), hashes.front().c_str()) != 0)
		{
			std::cerr << "###################################################" << std::endl;
			std::cerr << "WARNING: HASHES OF COMMUNICATION OBJECTS MISSMATCH!" << std::endl;
			std::cerr << "ROICore hash" << std::endl;
			std::cerr << "Expected: " << getCompiledHash() << std::endl;
			std::cerr << "Received: " << hashes.front() << std::endl;
			std::cerr << "###################################################" << std::endl;
		}
		assert(strcmp(getCompiledHash(), hashes.front().c_str()) == 0);
		hashes.pop_front();
		
		// check hash value(s) for CommObjectRecognitionObjects::CommPoint2d(idl_ROI.point)
		CommObjectRecognitionObjects::CommPoint2d::checkAllHashValues(hashes);
	}
	
	#ifdef ENABLE_HASH
	size_t ROICore::generateDataHash(const DATATYPE &data)
	{
		size_t seed = 0;
		
		seed += CommObjectRecognitionObjects::CommPoint2d::generateDataHash(data.point);
		boost::hash_combine(seed, data.width);
		boost::hash_combine(seed, data.height);
		
		return seed;
	}
	#endif
	
	// default constructor
	ROICore::ROICore()
	:	idl_ROI()
	{  
		setPoint(CommObjectRecognitionObjects::CommPoint2d());
		setWidth(0.0);
		setHeight(0.0);
	}
	
	ROICore::ROICore(const DATATYPE &data)
	:	idl_ROI(data)
	{  }

	ROICore::~ROICore()
	{  }
	
	void ROICore::to_ostream(std::ostream &os) const
	{
	  os << "ROI(";
	  getPoint().to_ostream(os);
	  os << getWidth() << " ";
	  os << getHeight() << " ";
	  os << ") ";
	}
	
	// convert to xml stream
	void ROICore::to_xml(std::ostream &os, const std::string &indent) const {
		os << indent << "<point>";
		getPoint().to_xml(os, indent);
		os << indent << "</point>";
		os << indent << "<width>" << getWidth() << "</width>";
		os << indent << "<height>" << getHeight() << "</height>";
	}
	
	// restore from xml stream
	void ROICore::from_xml(std::istream &is) {
		static const Smart::KnuthMorrisPratt kmp_point("<point>");
		static const Smart::KnuthMorrisPratt kmp_width("<width>");
		static const Smart::KnuthMorrisPratt kmp_height("<height>");
		
		if(kmp_point.search(is)) {
			CommObjectRecognitionObjects::CommPoint2d pointItem;
			pointItem.from_xml(is);
			setPoint(pointItem);
		}
		if(kmp_width.search(is)) {
			double widthItem;
			is >> widthItem;
			setWidth(widthItem);
		}
		if(kmp_height.search(is)) {
			double heightItem;
			is >> heightItem;
			setHeight(heightItem);
		}
	}
	
	/*
	void ROICore::get(ACE_Message_Block *&msg) const
	{
		// start with a default internal buffer size(will automatically grow if needed)
		ACE_OutputCDR cdr(ACE_DEFAULT_CDR_BUFSIZE);
		
		CommObjectRecognitionObjectsIDL::HashList hashes;
		getAllHashValues(hashes);
		cdr << static_cast<ACE_CDR::Long>(hashes.size());
		for(CommObjectRecognitionObjectsIDL::HashList::const_iterator it=hashes.begin(); it!=hashes.end(); it++)
		{
			cdr << ACE_CString(it->c_str());
		}
		
		// Here the actual serialization takes place using the OutputCDR serialization operator<<
		// (see ROIACE.hh)
		cdr << idl_ROI;
		
	#ifdef ENABLE_HASH
		ACE_CDR::ULong data_hash = generateDataHash(idl_ROI);
		cdr << data_hash;
		// std::cout << "ROICore: current data hash: " << data_hash << std::endl;
	#endif
		
		// return a shallow copy of the serialized message 
		// (no data is actually copied, only the internal reference counter is incremented)
		// in order to prevent memory leaks the caller of this get(msg) method must
		// manually free the memory by calling the release() method of the message block msg
		msg = cdr.begin()->duplicate();
	}
	
	void ROICore::set(const ACE_Message_Block *msg)
	{
		ACE_InputCDR cdr(msg);
	
		CommObjectRecognitionObjectsIDL::HashList hashes;
		ACE_CDR::Long hashes_size;
		cdr >> hashes_size;
		for(int i=0; i<hashes_size; ++i) 
		{
			ACE_CString hash;
			cdr >> hash;
			hashes.push_back(hash.c_str());
		}
		checkAllHashValues(hashes);
		
		// Here the actual de-serialization takes place using the InputCDR serialization operator>>
		// (see ROIACE.hh)
		cdr >> idl_ROI;
		
	#ifdef ENABLE_HASH
		ACE_CDR::Long data_hash;
		cdr >> data_hash;
		ACE_CDR::Long own_hash = generateDataHash(idl_ROI);
		assert(data_hash == own_hash);
		// std::cout << "ROICore: own data hash: " << own_hash << "; received data hash: " << data_hash << std::endl;
	#endif
	}
	*/
} /* namespace CommObjectRecognitionObjects */
