//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMOBJECTRECOGNITIONOBJECTS_SHAPE_CORE_H_
#define COMMOBJECTRECOGNITIONOBJECTS_SHAPE_CORE_H_

#include "CommObjectRecognitionObjects/ShapeData.hh"
#include "CommObjectRecognitionObjects/enumShapes.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommObjectRecognitionObjects {
	
class ShapeCore {
protected:
	// data structure
	CommObjectRecognitionObjectsIDL::Shape idl_Shape;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommObjectRecognitionObjectsIDL::Shape DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	ShapeCore();
	ShapeCore(const DATATYPE &data);
	// default destructor
	virtual ~ShapeCore();
	
	const DATATYPE& get() const { return idl_Shape; }
	operator const DATATYPE&() const { return idl_Shape; }
	DATATYPE& set() { return idl_Shape; }

	static inline std::string identifier(void) { return "CommObjectRecognitionObjects::Shape"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Name
	inline CommObjectRecognitionObjects::Shapes getName() const { return CommObjectRecognitionObjects::Shapes(idl_Shape.name); }
	inline ShapeCore& setName(const CommObjectRecognitionObjects::Shapes &name) { idl_Shape.name = name; return *this; }
};

} /* namespace CommObjectRecognitionObjects */
#endif /* COMMOBJECTRECOGNITIONOBJECTS_SHAPE_CORE_H_ */
